- name: Run Scraper Script
    env: 
      # שינינו את השמות כאן כדי שיתאימו לקוד החדש
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
    run: python perfume_bot.py
