name: Fragrantica Pushover Bot

on:
  schedule:
    # מריץ את הבוט כל שעה עגולה (למשל 14:00, 15:00...)
    # ההמתנה הרנדומלית בקוד הפייתון תדאג שהגישה לאתר לא תהיה בדיוק ב-:00
    - cron: '0 * * * *'
  
  # מאפשר הרצה ידנית לצורך בדיקות
  workflow_dispatch:

permissions:
  contents: write # חובה כדי לשמור את השינויים בגיט

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper Script
        env:
          # משתני Pushover
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          
          # משתנה בסיס הנתונים (התיקון החשוב!)
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
        run: python perfume_bot.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # מוריד שינויים מהשרת לפני שדוחף (מונע התנגשויות)
          git pull --rebase origin main
          
          git add last_seen_perfume.txt
          git commit -m "Update last seen perfume" || echo "No changes to commit"
          git push
